#!/bin/sh


SMALL=30x18
LARGE=100x60


for fn in *.GIF
do
	# get first 4 chars of filename	
	prefix=`echo $fn | cut -c 1-4`
	# make it lowercase
	prefix=`echo $prefix | tr "[A-Z]" "[a-z]"`		


	outfile=../cs-${prefix}.gif
	echo $outfile

	convert -size $SMALL $fn -resize $SMALL $outfile

	outfile=../c-${prefix}.gif
	echo $outfile
	convert -size $LARGE $fn -raise 8x8 -resize $LARGE $outfile
done


