#!/bin/sh

cd `echo $0 | sed -e s/[^/]*$//`
. ../../.config/bzlsql.php


if [ $# -eq 0 ]; then
	echo "USAGE: sqldumpbz tablename [tablename tablename ...]"
	echo "     Output sent to stdout"
	exit 5
fi


mysqldump  --add-drop-table -u $SQLuser --host=$SQLhost -p$SQLpass $SQLdatabase $*
