#!/bin/bash

## cd to where this script is
cd `echo $0 | sed -e s/[^/]*$//`

. ../../.config/bzlsql.php

 
echo "import league database from gzip backup"
 
if [ "$1" == "" ]; then
        echo "Specify an input file"
        exit 5
fi

echo "** This will delete all data in the $SQLdatabase sql database **"
echo "Hit control-C now to abort"
read 

echo "Dropping all tables ..."
cd create_new_install
php drop_all_tables.php

echo "Importing data from $1 ..."
cd ..
gunzip -c $1  | ./sql
